### PR TITLE
Fix rich editor tooltip typo for insert attachments button

### PR DESCRIPTION
**Pull request by liuchangfitcloud**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
修复富文本编辑器中鼠标移动到插入附件的提示信息

#### Which issue(s) this PR fixes:
Fixes https://github.com/halo-dev/halo/issues/2802

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by guqing — COMMENTED** [review]
/lgtm

**Comment by guqing** [comment]
> [CLA assistant check](https://cla-assistant.io/halo-dev/console?pullRequest=734) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/console?pullRequest=734) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/console?pullRequest=734) it.

@liuchangfitcloud 需要签署一下 CLA

**Review by JohnNiang — COMMENTED** [review]
/approve

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Pull request merged**
