### PR TITLE
feat: add display theme location support

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/kind feature
/milestone 2.0

#### What this PR does / why we need it:

添加显示主题存储位置的支持。适配 https://github.com/halo-dev/halo/pull/2484

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/2461

#### Screenshots:

image

#### Special notes for your reviewer:

测试方式：

1. Halo 需要切换到 https://github.com/halo-dev/halo/pull/2484 PR 的分支。
2. Console 需要 `pnpm install`
3. 上传新的主题，查看主题详情是否包含存储位置

#### Does this PR introduce a user-facing change?

```release-note
添加显示主题存储位置的支持
```

### CODE REVIEW

**Review by guqing — COMMENTED** [review]
/lgtm

**Review by JohnNiang — CHANGES_REQUESTED** [review]
Please resolve the conflicts before merging.

**Review by guqing — COMMENTED** [review]
/lgtm

**Review by JohnNiang — APPROVED** [review]
/approve

**Pull request merged**
