### PR TITLE
chore: release 2.3.2

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/kind improvement

#### What this PR does / why we need it:

发布 Console 2.3.2

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by JohnNiang — APPROVED** [review]
/approve

**Review by guqing — COMMENTED** [review]
/lgtm

**Comment by JohnNiang** [comment]
/unhold

Unhold due to https://github.com/halo-dev/console/pull/913 merged.

**Pull request merged**
