### PR TITLE
refactor: use generateName instead of uuid to generate metadata.name

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/kind improvement
/milestone 2.0

#### What this PR does / why we need it:

使用 metadata.generateName 代替 uuid 为 metadata.name 生成值。

Ref https://github.com/halo-dev/halo/pull/2563

#### Special notes for your reviewer:

/cc @halo-dev/sig-halo-console 

测试方式：

1. 需要 `pnpm install`
2. 测试登录以及所有需要创建更新资源的业务模块。

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by ruibaby** [comment]
/retitle WIP: refactor: use generateName instead of uuid to generate metadata.name

**Comment by ruibaby** [comment]
/retitle refactor: use generateName instead of uuid to generate metadata.name

**Comment by JohnNiang** [comment]
Please resolve the conflicts before reviewing.

**Comment by ruibaby** [comment]
> Please resolve the conflicts before reviewing.

Done

**Review by guqing — COMMENTED** [review]
/lgtm

**Review by JohnNiang — APPROVED** [review]
/approve

**Pull request merged**
