### PR TITLE
fix: post list showing the number of post in the tags

### PR DESCRIPTION
**Pull request by BoWang816**
#### What type of PR is this?
bug

#### What this PR does / why we need it:
to fix the parenthesis problem of article list labels

#### Which issue(s) this PR fixes:

Fixes #

#### Screenshots:
Before：
image

After：
image

#### Does this PR introduce a user-facing change?

```release-note
优化文章列表标签显示
```

### CODE REVIEW

**Comment by ruibaby** [comment]
@BoWang816 在合并前请按照 https://github.com/halo-dev/console/pull/650#issuecomment-1282317696 签署我们的 CLA。

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Review by guqing — COMMENTED** [review]
/lgtm

**Review by ruibaby — APPROVED** [review]
/approve

**Pull request merged**
