### PR TITLE
docs: update readme for Halo 2.0

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/kind documentation
/milestone 2.0

#### What this PR does / why we need it:

更新 README

#### Special notes for your reviewer:

/cc @halo-dev/sig-halo-console 

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by ruibaby** [comment]
https://github.com/ruibaby/halo-console/tree/docs/update-readme-for-2.0

**Comment by ruibaby** [comment]
Preview https://github.com/ruibaby/halo-console/tree/docs/update-readme-for-2.0

**Review by guqing — COMMENTED** [review]
/lgtm

**Review by JohnNiang — APPROVED** [review]
/approve

**Pull request merged**
