### PR TITLE
perf: improve the prompt for upload failure of the upload component

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/kind improvement

#### What this PR does / why we need it:

优化上传组件的异常提示信息。

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/2933
Ref https://github.com/halo-dev/halo/issues/2932 https://github.com/halo-dev/halo/issues/2931

#### Screenshots:

image
image

#### Special notes for your reviewer:

测试方式：

1. 进入附件上传、插件安装、主题安装界面。
2. 上传不符合规则的文件，比如主题可以上传一个不是主题的 zip 或者 Halo 1.x 版本的 zip。
3. 观察是否有异常提示。

#### Does this PR introduce a user-facing change?

```release-note
优化 Console 端上传组件的异常提示信息。
```

### CODE REVIEW

**Review by JohnNiang — APPROVED** [review]
It works very well.

image

/approve

**Review by guqing — COMMENTED** [review]
/lgtm

**Comment by JohnNiang** [comment]
将这些修改应用到 release-2.0 分支如何？

**Pull request merged**
