### PR TITLE
fix: the width of the code input type is not full

### PR DESCRIPTION
**Pull request by infanx**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
修复 Console 端 FormKit 的 Code 输入类型宽度异常

#### Which issue(s) this PR fixes:

Fixes # https://github.com/halo-dev/halo/issues/3227

#### Does this PR introduce a user-facing change?

```release-note
修复 Console 端 FormKit 的 Code 输入框宽度未占满的问题
```

### CODE REVIEW

**Review by ruibaby — APPROVED** [review]
/approve

Thanks for your first contribution!

**Comment by guqing** [comment]
Hi @infanx, 合并前需要先根据 https://github.com/halo-dev/console/pull/838#issuecomment-1419181020 签署一下 CLA

**Review by guqing — COMMENTED** [review]
/lgtm

**Comment by guqing** [comment]
Hi @infanx，在合并前需要先根据 https://github.com/halo-dev/console/pull/838#issuecomment-1419181020 签署一下CLA

**Pull request merged**
