### PR TITLE
perf: improve the text of the upgrade theme button

### PR DESCRIPTION
**Pull request by Joydevelop**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

修改主题升级文案

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/2857

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by ruibaby** [comment]
@Joydevelop 请按照 https://github.com/halo-dev/console/pull/747#issuecomment-1338965325 签署一下我们的 CLA 协议。

**Comment by ruibaby** [comment]
/retitle perf: improve the text of the upgrade theme button

**Review by JohnNiang — APPROVED** [review]
/approve

**Review by guqing — COMMENTED** [review]
/lgtm

**Pull request merged**
