### PR TITLE
fix: the global search keyboard event is not removed when the component is unmounted

### PR DESCRIPTION
**Pull request by wzrove**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

image

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/2927

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by ruibaby — APPROVED** [review]
/approve

Great!

**Review by guqing — COMMENTED** [review]
/lgtm

**Pull request merged**
