### PR TITLE
refactor: plugin author field

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/kind improvement
/milestone 2.0

#### What this PR does / why we need it:

修改插件的 author 字段为对象形式。适配 https://github.com/halo-dev/halo/pull/2806

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by guqing — COMMENTED** [review]
/approve
works very good

**Comment by ruibaby** [comment]
> Please resolve the conflict first.

Done

**Comment by guqing** [comment]
重新生成以下 API client, 刚刚 https://github.com/halo-dev/halo/pull/2806 刚刚改过类名

**Review by JohnNiang — APPROVED** [review]
/lgtm

**Pull request merged**
