### PR TITLE
fix: native login box pops up when the session expires

### PR DESCRIPTION
**Pull request by longjuan**
#### What type of PR is this?
/kind improvement
/area console

#### What this PR does / why we need it:
添加`X-Requested-With=XMLHttpRequest`请求头，以阻止spring security 带上`WWW-Authenticate`响应头导致弹出原生登录框。
#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/3213

#### Special notes for your reviewer:
使session过期后（直接删除cookie的session或重启后端），继续操作console端，预期不会弹出原生登录框且console端原有的重新登录form正常弹出。
详情https://spring.io/guides/tutorials/spring-security-and-angular-js/ 中搜索X-Requested-With
#### Does this PR introduce a user-facing change?

```release-note
防止浏览器弹出原生登录框
```

### CODE REVIEW

**Review by ruibaby — APPROVED** [review]
/approve

**Review by guqing — COMMENTED** [review]
/lgtm

**Pull request merged**
