### PR TITLE
fix: timeout error caused by upload processing for more than 30 seconds

### PR DESCRIPTION
**Pull request by longjuan**
#### What type of PR is this?

/kind improvement
#### What this PR does / why we need it:
Remove the timeout error prompt caused by the upload server processing for more than 30 seconds
#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/3041
#### Screenshots:

image
image

#### Special notes for your reviewer:
测试：
上传大文件让后端处理过程超过30秒，观察是否报错
或使用[修改后的插件](https://github.com/longjuan/halo-plugin-s3os/actions/runs/3852075387)上传到对象存储，观察61秒后是否上传成功
#### Does this PR introduce a user-facing change?

```release-note
去除上传文件处理时间超过30秒后的报错
```

### CODE REVIEW

**Review by ruibaby — APPROVED** [review]
/approve

Nice work!

**Review by JohnNiang — APPROVED** [review]
/lgtm

**Pull request merged**
