### PR TITLE
fix: the issue that role display name

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/kind improvement

#### What this PR does / why we need it:

为系统初始化的角色添加显示名称

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/3257

#### Screenshots:

image

#### Special notes for your reviewer:

测试方式：

1. Halo 需要切换到：https://github.com/halo-dev/halo/pull/3280
2. 检查 Console 端显示的系统角色是否正常。
3. 新建若干自定义角色，检查名称是否正常。

#### Does this PR introduce a user-facing change?

```release-note
优化 Console 端用户角色标识的显示名称。
```

### CODE REVIEW

**Review by guqing — COMMENTED** [review]
/lgtm

**Comment by ruibaby** [comment]
@halo-dev/sig-halo-console

**Review by JohnNiang — APPROVED** [review]
It works very well.

/approve

**Pull request merged**
