### PR TITLE
refactor: update the field for the number of post under categories and tags

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/kind improvement
/milestone 2.0

#### What this PR does / why we need it:

修改标签/分类显示文章数量的字段。 适配 https://github.com/halo-dev/halo/pull/2483

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

测试方式：

1. Halo 需要切换到 https://github.com/halo-dev/halo/pull/2483 PR 中的分支。
2. Console 需要 `pnpm install`
3. 发布多篇带分类和标签的文章后，检查分类和标签的文章数量是否正确。

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by guqing — COMMENTED** [review]
/approve

**Review by JohnNiang — APPROVED** [review]
/approve

**Comment by JohnNiang** [comment]
建议解决一下 Check 错误，可参考：<https://github.com/halo-dev/console/actions/runs/3148245557/jobs/5118574411>。

**Review by guqing — COMMENTED** [review]
/approve

**Pull request merged**
