### PR TITLE
refactor: add loading states for data list

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/kind improvement
/milestone 2.0

#### What this PR does / why we need it:

优化列表的加载，添加加载动画，解决加载完成之后界面闪动的问题。

#### Which issue(s) this PR fixes:

Ref https://github.com/halo-dev/halo/issues/2370

#### Special notes for your reviewer:

/cc @halo-dev/sig-halo-console 

#### Does this PR introduce a user-facing change?

```release-note
优化列表的加载，添加加载动画，解决加载完成之后界面闪动的问题。
```

### CODE REVIEW

**Review by guqing — COMMENTED** [review]
/lgtm

**Comment by JohnNiang** [comment]
Please resolve conflicts first.

**Comment by ruibaby** [comment]
> Please resolve conflicts first.

Done

**Review by JohnNiang — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
