### PR TITLE
feat: add supports for preview audio and video file in attachment detail

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

支持在附件库的附件详情弹框中预览音视频文件。

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/1923

#### Screenshots:

image
image

#### Special notes for your reviewer:

测试方式：

1. 上传若干视频和音频文件，检查是否可以正常播放即可。

可供测试的文件：[音视频测试.zip](https://github.com/halo-dev/console/files/10694553/default.zip)

#### Does this PR introduce a user-facing change?

```release-note
Console 端的附件详情支持预览音视频文件。
```

### CODE REVIEW

**Review by guqing — COMMENTED** [review]
/lgtm

**Comment by ruibaby** [comment]
@halo-dev/sig-halo-console

**Review by JohnNiang — APPROVED** [review]
It works very well.

image

/approve

**Pull request merged**
