### PR TITLE
feat: add supports for download log file in actuator page

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

在系统概览页面支持下载运行日志。

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/3188

#### Screenshots:

image

#### Special notes for your reviewer:

测试方式：

1. 进入系统概览页面，点击运行日志的下载按钮。
2. 检查是否成功下载了日志文件。

#### Does this PR introduce a user-facing change?

```release-note
Console 端的系统概览页面支持下载运行日志。
```

### CODE REVIEW

**Comment by ruibaby** [comment]
/hold 

后端需要默认开启 logfile 的 actuator 入口。

**Comment by ruibaby** [comment]
/unhold

Halo 在 https://github.com/halo-dev/halo/pull/3345 中已支持。

**Review by guqing — COMMENTED** [review]
/lgtm

**Review by JohnNiang — APPROVED** [review]
It works very well for me.

image

/approve

**Pull request merged**
